from pr_agent.git_providers.git_provider import GitProvider


class DummyProvider(GitProvider):
    def __init__(self, description: str):
        self.description = description

    def get_pr_description_full(self) -> str:
        return self.description

    def is_supported(self, capability: str) -> bool:
        return False

    def get_files(self) -> list:
        return []

    def get_diff_files(self) -> list:
        return []

    def publish_description(self, pr_title: str, pr_body: str):
        pass

    def publish_code_suggestions(self, code_suggestions: list) -> bool:
        return True

    def get_languages(self):
        return {}

    def get_pr_branch(self):
        return ""

    def get_user_id(self):
        return ""

    def get_repo_settings(self):
        return ""

    def publish_inline_comment(self, body: str, relevant_file: str, relevant_line_in_file: str, original_suggestion=None):
        pass

    def publish_inline_comments(self, comments: list[dict]):
        pass

    def remove_initial_comment(self):
        pass

    def publish_comment(self, pr_comment: str, is_temporary: bool = False):
        pass

    def remove_comment(self, comment):
        pass

    def get_issue_comments(self):
        return []

    def publish_labels(self, labels):
        pass

    def get_pr_labels(self, update=False):
        return []

    def add_eyes_reaction(self, issue_comment_id: int, disable_eyes: bool = False):
        return None

    def remove_reaction(self, issue_comment_id: int, reaction_id: int) -> bool:
        return False

    def get_commit_messages(self):
        return ""


def test_get_user_description_skips_generated_by_header_before_user_section():
    description = """### 🤖 Generated by PR Agent at abc123

### **User description**
Manual description only.

___

### **PR Type**
Enhancement

___

### **Description**
Generated summary that should not be preserved as user text.
"""

    provider = DummyProvider(description)

    assert provider.get_user_description() == "Manual description only."
